#!/bin/bash
# ==============================================================================
# YARA rules updater: our own rules + upstream community signature collection
# Installed to /usr/local/bin/update-yara-rules.sh by install.sh
# Builds /var/ossec/yara/rules/index.yar which yara.sh scans with.
#
# signature-base rules use external vars (filename/filepath/extension/
# filetype/owner) - the AR script defines them with -d, and so do the
# compile checks below. Files that still fail to compile (missing modules,
# THOR-only) are dropped individually.
# ==============================================================================
set -u

OWN_RULES_URL="https://raw.githubusercontent.com/minhtawlwe-svg/wazuh/git-home/yara/rule-collection/yara_rules.yar"
SIGBASE_TARBALL="https://github.com/Neo23x0/signature-base/archive/refs/heads/master.tar.gz"

RULES_DIR="/var/ossec/yara/rules"
SIGBASE_DIR="$RULES_DIR/signature-base"
INDEX="$RULES_DIR/index.yar"
LOG="/var/log/yara-update.log"
EXTVARS=(-d filename="" -d filepath="" -d extension="" -d filetype="" -d owner="")

log() { echo "[$(date)] $*" >> "$LOG"; echo "$*"; }

compiles() { yara -w "${EXTVARS[@]}" "$1" /dev/null > /dev/null 2>&1; }

mkdir -p "$RULES_DIR"
log "Starting YARA rules update..."

# ---- 1. Our own rules --------------------------------------------------------
if curl -fsSL "$OWN_RULES_URL" -o "$RULES_DIR/yara_rules.yar.new" && compiles "$RULES_DIR/yara_rules.yar.new"; then
    mv "$RULES_DIR/yara_rules.yar.new" "$RULES_DIR/yara_rules.yar"
    log "Own rules updated OK."
else
    rm -f "$RULES_DIR/yara_rules.yar.new"
    log "ERROR: own rules download/compile failed; keeping previous copy."
fi

# ---- 2. signature-base -------------------------------------------------------
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
if curl -fsSL "$SIGBASE_TARBALL" -o "$TMP/sb.tar.gz" && tar -xzf "$TMP/sb.tar.gz" -C "$TMP"; then
    SRC=$(find "$TMP" -maxdepth 2 -type d -name yara | head -1)
    if [ -n "$SRC" ]; then
        mkdir -p "$SIGBASE_DIR.new"
        kept=0; dropped=0
        for f in "$SRC"/*.yar; do
            base=$(basename "$f")
            # Known THOR-only / module-dependent sets that never compile with stock yara
            case "$base" in
                thor_inverse_matches.yar|yara_mixed_ext_vars.yar|configured_vulns_ext_vars.yar|expl_*_vuln_*.yar) dropped=$((dropped+1)); continue ;;
            esac
            if compiles "$f"; then
                cp "$f" "$SIGBASE_DIR.new/"; kept=$((kept+1))
            else
                dropped=$((dropped+1))
            fi
        done
        if [ "$kept" -gt 0 ]; then
            rm -rf "$SIGBASE_DIR"
            mv "$SIGBASE_DIR.new" "$SIGBASE_DIR"
            log "signature-base updated: $kept files kept, $dropped dropped (incompatible)."
        else
            rm -rf "$SIGBASE_DIR.new"
            log "ERROR: no signature-base file compiled; keeping previous copy."
        fi
    else
        log "ERROR: signature-base yara dir not found in tarball."
    fi
else
    log "ERROR: signature-base download failed; keeping previous copy."
fi

# ---- 3. Build master index ---------------------------------------------------
{
    echo "// Auto-generated by update-yara-rules.sh - do not edit"
    [ -f "$RULES_DIR/yara_rules.yar" ] && echo "include \"$RULES_DIR/yara_rules.yar\""
    if [ -d "$SIGBASE_DIR" ]; then
        for f in "$SIGBASE_DIR"/*.yar; do echo "include \"$f\""; done
    fi
} > "$INDEX.new"

if compiles "$INDEX.new"; then
    mv "$INDEX.new" "$INDEX"
    log "index.yar rebuilt OK ($(grep -c '^include' "$INDEX") rule files)."
else
    # Fall back: drop includes that break the combined compile (duplicate rule names, etc.)
    log "Combined index failed compile; pruning conflicting files..."
    echo "// Auto-generated by update-yara-rules.sh - do not edit" > "$INDEX.new"
    [ -f "$RULES_DIR/yara_rules.yar" ] && echo "include \"$RULES_DIR/yara_rules.yar\"" >> "$INDEX.new"
    if [ -d "$SIGBASE_DIR" ]; then
        for f in "$SIGBASE_DIR"/*.yar; do
            echo "include \"$f\"" >> "$INDEX.new"
            if ! compiles "$INDEX.new"; then
                sed -i '$d' "$INDEX.new"
            fi
        done
    fi
    mv "$INDEX.new" "$INDEX"
    log "index.yar rebuilt with pruning ($(grep -c '^include' "$INDEX") rule files)."
fi

# ---- 4. Restart agent so next AR uses fresh rules ----------------------------
if systemctl is-active --quiet wazuh-agent; then
    systemctl restart wazuh-agent
    log "wazuh-agent restarted."
fi
log "YARA rules update finished."
